# Dangerous commands and patterns to block
commands:
  # Destructive file operations
  - "rm -rf /"
  - "rm -rf /*"
  - "rm -rf ~"
  - "rm -rf $HOME"
  - "dd if=/dev/zero"
  - "mkfs"
  - "fdisk"
  - "parted"
  
  # System modification
  - "sudo"
  - "su -"
  - "chmod 777"
  - "chown root"
  - "systemctl"
  - "service"
  
  # Network security risks
  - "curl | bash"
  - "wget | sh"
  - "curl | sh"
  - "bash <(curl"
  - "bash <(wget"
  
  # Package managers (require explicit approval)
  - "apt-get install"
  - "yum install"
  - "dnf install"
  - "pacman -S"
  - "brew install"
  - "npm install -g"
  - "pip install"
  
  # Process manipulation
  - "kill -9 -1"
  - "killall -9"
  - "pkill -f"

patterns:
  # Regex patterns for dangerous operations
  - "rm\\s+-rf\\s+/"
  - "chmod\\s+777\\s+"
  - "\\|\\s*bash"
  - "\\|\\s*sh"
  - ">/dev/sd[a-z]"
  - "format\\s+[A-Z]:"
  - "del\\s+/[qsf]"

# High-risk operations that require explicit confirmation
highRisk:
  - "git reset --hard"
  - "git clean -fd"
  - "docker system prune"
  - "npm ci"
  - "mvn clean"
  - "gradle clean"